<a href="https://colab.research.google.com/github/LaiTechTinker/LLMpract/blob/master/LLM_tokenizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
# filepath=drive.mount('/content/drive/My Drive/LLM_pract/the-verdict.txt')
drive.mount('/content/drive')
# real_Path=drive.mount(filepath)
# with open(real_Path,'r',encoding='utf-8') as f:
#  text=f.read()
# print(text)

Mounted at /content/drive


In [2]:
filepath='/content/drive/My Drive/LLM_pract/the-verdict.txt'
with open(filepath,'r',encoding='utf-8') as f:
  text=f.read()
print(len(text))

20479


In [3]:
print(text[:99])

I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no 


In [4]:
# import re
# re_text="hello, world. This i a text"
# result=re.split(r'([,.]\s)',re_text)
# new_result=[item.strip() for item in result]
# print(result)
# print(new_result)

In [5]:
# result=re.split(r'([,.?-_!:"\']\s)',text)
# new_result=[item.strip() for item in result]
# print(new_result[:120])

In [6]:
import re
result = re.split(r'([,.:;?_!"()\']|--|\s)', text)
preprocessed = [item.strip() for item in result if item.strip()]
print(preprocessed[:100])

['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in', 'the', 'height', 'of', 'his', 'glory', ',', 'he', 'had', 'dropped', 'his', 'painting', ',', 'married', 'a', 'rich', 'widow', ',', 'and', 'established', 'himself', 'in', 'a', 'villa', 'on', 'the', 'Riviera', '.', '(', 'Though', 'I', 'rather', 'thought', 'it', 'would', 'have', 'been', 'Rome', 'or', 'Florence', '.', ')', '"', 'The', 'height', 'of', 'his', 'glory', '"', '--', 'that', 'was', 'what', 'the', 'women', 'called', 'it', '.', 'I', 'can', 'hear', 'Mrs', '.', 'Gideon', 'Thwing', '--', 'his', 'last', 'Chicago', 'sitter', '--']


In [7]:
print(len(preprocessed))

4690


In [8]:
allwords=sorted(set(preprocessed))
print(len(allwords))

1130


In [9]:
vocab={word:index for index,word in enumerate(allwords)}
for i,word in enumerate(vocab.items()):
  print(word)
  if i ==50:
    break

('!', 0)
('"', 1)
("'", 2)
('(', 3)
(')', 4)
(',', 5)
('--', 6)
('.', 7)
(':', 8)
(';', 9)
('?', 10)
('A', 11)
('Ah', 12)
('Among', 13)
('And', 14)
('Are', 15)
('Arrt', 16)
('As', 17)
('At', 18)
('Be', 19)
('Begin', 20)
('Burlington', 21)
('But', 22)
('By', 23)
('Carlo', 24)
('Chicago', 25)
('Claude', 26)
('Come', 27)
('Croft', 28)
('Destroyed', 29)
('Devonshire', 30)
('Don', 31)
('Dubarry', 32)
('Emperors', 33)
('Florence', 34)
('For', 35)
('Gallery', 36)
('Gideon', 37)
('Gisburn', 38)
('Gisburns', 39)
('Grafton', 40)
('Greek', 41)
('Grindle', 42)
('Grindles', 43)
('HAD', 44)
('Had', 45)
('Hang', 46)
('Has', 47)
('He', 48)
('Her', 49)
('Hermia', 50)


In [10]:
class Tokenizer:
  def __init__(self,vocab):
    self.str_to_int=vocab
    self.int_to_str={i:s for s,i in vocab.items()}
  def encode(self, text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)

        preprocessed = [
            item.strip() for item in preprocessed if item.strip()
        ]
        ids=[]
        for s in preprocessed:
          if s not in self.str_to_int:
            continue
          ids.append(self.str_to_int[s])
        return ids

  def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        # Replace spaces before the specified punctuations
        text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
        return text

In [11]:
all_tokens = sorted(list(set(preprocessed)))
all_tokens.extend(["<|endoftext|>", "<|unk|>"])

vocab = {token:integer for integer,token in enumerate(all_tokens)}

In [12]:
len(vocab.items())

1132

In [13]:
for i, item in enumerate(list(vocab.items())[-5:]):
    print(item)

('younger', 1127)
('your', 1128)
('yourself', 1129)
('<|endoftext|>', 1130)
('<|unk|>', 1131)


In [14]:
class tokenizerV2:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = { i:s for s,i in vocab.items()}

    def encode(self, text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
        preprocessed = [item.strip() for item in preprocessed if item.strip()]
        preprocessed = [
            item if item in self.str_to_int
            else "<|unk|>" for item in preprocessed # the <unk> will be unknown with the largest integer
        ]

        ids = [self.str_to_int[s] for s in preprocessed]
        return ids

    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        # Replace spaces before the specified punctuations
        text = re.sub(r'\s+([,.:;?!"()\'])', r'\1', text)
        # return text(r'\s+([,.?!"()\'])', r'\1', text)
        return text

In [15]:
tokenizer = Tokenizer(vocab)

text = """"It's the last he painted, you know,"
           Mrs. Gisburn said with pardonable pride."""
ids = tokenizer.encode(text)
print(ids)

[1, 56, 2, 850, 988, 602, 533, 746, 5, 1126, 596, 5, 1, 67, 7, 38, 851, 1108, 754, 793, 7]


In [16]:
tokenizer = tokenizerV2(vocab)

text1 = "Hello, do you like tea?"
text2 = "In the sunlit terraces of the palace."

text = " <|endoftext|> ".join((text1, text2))

print(text)

Hello, do you like tea? <|endoftext|> In the sunlit terraces of the palace.


In [17]:
tokenizer.encode(text)

[1131, 5, 355, 1126, 628, 975, 10, 1130, 55, 988, 956, 984, 722, 988, 1131, 7]

In [18]:
ids = tokenizer.encode(text)
tokenizer.decode(ids)

'<|unk|>, do you like tea? <|endoftext|> In the sunlit terraces of the <|unk|>.'

In [19]:
import tiktoken
tokenizer=tiktoken.get_encoding("gpt2")


In [20]:
text=("hello, do you like tea?<|endoftext|> In the sunlit terrace""of someunlnowpalce")
ids=tokenizer.encode(text,allowed_special={"<|endoftext|>"})
strings=tokenizer.decode(ids)
print(ids)
print(strings)

[31373, 11, 466, 345, 588, 8887, 30, 50256, 554, 262, 4252, 18250, 8812, 558, 1659, 617, 403, 75, 2197, 18596, 344]
hello, do you like tea?<|endoftext|> In the sunlit terraceof someunlnowpalce


In [21]:
import tiktoken
enc = tiktoken.get_encoding("o200k_base")
ids=enc.encode(text,allowed_special={"<|endoftext|>"})
print(ids)



[24912, 11, 621, 481, 1299, 17966, 30, 199999, 730, 290, 7334, 32758, 51551, 1440, 1236, 373, 2943, 384, 18413, 400]


Creating input target pairs


In [22]:
with open(filepath,'r',encoding="utf-8") as f:
  text=f.read()
enc_text=enc.encode(text,allowed_special={"<|endoftext|>"})
print(len(enc_text))


4836


In [23]:
enc_sample=enc_text[50:]
print(enc_sample)

[11166, 306, 261, 38350, 402, 290, 123397, 13, 350, 52861, 357, 7542, 4525, 480, 1481, 679, 1339, 27388, 503, 62520, 16803, 30289, 4679, 328, 1232, 40373, 150535, 14116, 673, 1412, 290, 5142, 4358, 480, 13, 357, 665, 9598, 31127, 13, 183881, 263, 748, 3964, 375, 38520, 2174, 16864, 86581, 375, 613, 528, 7443, 1232, 537, 8218, 562, 65927, 4598, 13, 392, 2566, 4165, 4275, 2966, 316, 4952, 290, 1432, 328, 922, 8723, 461, 3499, 869, 26, 889, 357, 4128, 2411, 328, 484, 11, 9655, 13, 41767, 6595, 375, 3086, 6266, 316, 16880, 83, 382, 722, 357, 2411, 328, 3692, 623, 2195, 11, 402, 31127, 13, 748, 3964, 885, 36968, 11, 118583, 1617, 1175, 6435, 62, 472, 5495, 1023, 1504, 45264, 306, 448, 34768, 22932, 328, 62971, 13, 1958, 480, 673, 625, 1606, 290, 31127, 13, 748, 86, 963, 1218, 116720, 295, 13, 32183, 625, 290, 67557, 39779, 535, 25186, 826, 11, 540, 290, 2174, 499, 4055, 263, 28360, 2356, 11, 18145, 668, 2254, 165003, 33750, 885, 392, 97198, 2469, 39961, 1, 316, 2891, 11, 483, 37095, 306, 13

In [25]:
import torch
from torch.utils.data import Dataset,DataLoader


class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        # Tokenize the entire text
        token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})

        # Use a sliding window to chunk the book into overlapping sequences of max_length
        for i in range(0, len(token_ids) - max_length, stride):
            input_chunk = token_ids[i:i + max_length]
            target_chunk = token_ids[i + 1: i + max_length + 1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return self.input_ids[idx], self.target_ids[idx]

In [26]:
def create_dataloader_v1(txt, batch_size=4, max_length=256,
                         stride=128, shuffle=True, drop_last=True,
                         num_workers=0):

    # Initialize the tokenizer
    tokenizer = tiktoken.get_encoding("gpt2")

    # Create dataset
    dataset = GPTDatasetV1(text, tokenizer, max_length, stride)

    # Create dataloader
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers
    )

    return dataloader

In [27]:
print("PyTorch version:", torch.__version__)
dataloader = create_dataloader_v1(
    text, batch_size=4, max_length=8, stride=1, shuffle=False
)

data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)

PyTorch version: 2.6.0+cu124
[tensor([[   40,   367,  2885,  1464,  1807,  3619,   402,   271],
        [  367,  2885,  1464,  1807,  3619,   402,   271, 10899],
        [ 2885,  1464,  1807,  3619,   402,   271, 10899,  2138],
        [ 1464,  1807,  3619,   402,   271, 10899,  2138,   257]]), tensor([[  367,  2885,  1464,  1807,  3619,   402,   271, 10899],
        [ 2885,  1464,  1807,  3619,   402,   271, 10899,  2138],
        [ 1464,  1807,  3619,   402,   271, 10899,  2138,   257],
        [ 1807,  3619,   402,   271, 10899,  2138,   257,  7026]])]


In [28]:
dataloader = create_dataloader_v1(text, batch_size=8, max_length=4, stride=4, shuffle=False)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Inputs:\n", inputs)
print("\nTargets:\n", targets)

Inputs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Targets:
 tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])


In [29]:
import torch
from torch.nn import Linear

In [36]:
vocab_ids=torch.tensor([2,3,5,6])
vocab_size=6
feature_dim=4
torch.manual_seed(123)
embedded_layer=torch.nn.Embedding(vocab_size,feature_dim)
print(embedded_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.3035, -0.5880],
        [ 0.3486,  0.6603, -0.2196, -0.3792],
        [-0.1606, -0.4015,  0.6957, -1.8061],
        [ 1.8960, -0.1750,  1.3689, -1.6033],
        [-0.7849, -1.4096, -0.4076,  0.7953],
        [ 0.9985,  0.2212,  1.8319, -0.3378]], requires_grad=True)


In [38]:
print(embedded_layer(torch.tensor([2])))

tensor([[-0.1606, -0.4015,  0.6957, -1.8061]], grad_fn=<EmbeddingBackward0>)


In [49]:
vocab_size2=50257
feature_dim2=256
embeded_layer2=torch.nn.Embedding(vocab_size2,feature_dim2)
print(embeded_layer2.weight.shape)


torch.Size([50257, 256])


In [51]:
max_length = 4
dataloader = create_dataloader_v1(
    text, batch_size=8, max_length=max_length,
    stride=max_length, shuffle=False
)
data_iter = iter(dataloader)
inputs, targets = next(data_iter)

In [52]:
print("Token IDs:\n", inputs)
print("\nInputs shape:\n", inputs.shape)

Token IDs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Inputs shape:
 torch.Size([8, 4])


In [56]:
token_embedding=embeded_layer2(inputs)
print(token_embedding.shape)

torch.Size([8, 4, 256])


In [57]:
context_length = max_length
pos_embedding_layer = torch.nn.Embedding(context_length, feature_dim2)

In [58]:
pos_embeddings = pos_embedding_layer(torch.arange(max_length))
print(pos_embeddings.shape)

torch.Size([4, 256])


In [59]:
input_embeddings = token_embedding + pos_embeddings
print(input_embeddings.shape)

torch.Size([8, 4, 256])
